### ISSUE TITLE
web interface unavailable

### ISSUE THREAD

**Issue by BETLOG** [munin-monitoring/munin#1271]
**Describe the bug**
I am unable to access the graphs via http.
I have read dozens of explanations of how to rectify this, and been over hours of testing and reinstallation to try to rectify this.
This is not so much a bug report as:
- a statement : that installation and html viewing of munin is ridiculously elusive for some/many users.
- my settings and some observations.

Maybe someone can help.

Firstly:
Chrome :
 instantly reports 

> This site can’t be reachedThe connection was reset.
> ERR_CONNECTION_RESET

or

> This page isn’t working
> 192.168.178.30 sent an invalid response.
> ERR_INVALID_HTTP_RESPONSE

Firefox :
displays a blank page for (?several minutes?) until it times out, when it displays:
```
# munin node at pizero.fritz.box
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
```

I have installed munin on three machines now, probably for a total of 5 installations and then sanity-checking re-installations , and at no time been able to view it's logs via apache2.

```
/usr/sbin/apache2 -v
Server version: Apache/2.4.38 (Raspbian)
Server built:   2019-10-15T19:53:42
```

I *have* been able to view the graphs by putting 

> /var/cache/munin/www/index.html

into a browser.
However my current and hopefully final  install is on a raspberry pi zero, which I will operate headlessly. So accessing it's graphs directly via file structure the same way as before isn't as practical. I *need* to view them via http.

I have tried all sorts of variations on config files, but here is the latest iteration, at this point I basically give up, for now.

I didnt think a separate /etc/apache2/sites-available/ config was required, but at this point i'm grasping at straws:

/etc/apache2/sites-available/munin.conf
```
<VirtualHost *:4949> 
	ServerAdmin munin@localhost
	ServerName munin.fritz.box
	ServerAlias munin.local
	DocumentRoot /var/www/munin/
	ErrorLog /var/ww/munin/apache-error.log 
	CustomLog /var/www/munin/apache-access.log combined
</VirtualHost>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

Given that /etc/munin/apache.conf and /etc/munin/apache24.conf exist (apparently only apache24.conf on the latest install), I also straw-grasped by adjusting:

/etc/apache2/apache2.conf
```
ServerName localhost
Mutex file:${APACHE_LOCK_DIR} default
PidFile ${APACHE_PID_FILE}
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}
HostnameLookups Off
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

Include ports.conf

<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride None
	Require all granted
</Directory>

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>

<Directory /var/www/munin/>
	Options Indexes FollowSymLinks
        AllowOverride All
	Require all granted
</Directory>

AccessFileName .htaccess

<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf
```

/etc/munin/apache.conf
```
Alias /munin /var/www/munin
<Directory /var/www/munin>
        Order allow,deny
#         Allow from localhost 127.0.0.0/8 ::1        
        Allow from all
        Options None
    <IfModule mod_expires.c>
        ExpiresActive On
    	ExpiresDefault M310
    </IfModule>

</Directory> 
ScriptAlias /munin-cgi/munin-cgi-graph /usr/lib/munin/cgi/munin-cgi-graph
<Location /munin-cgi/munin-cgi-graph>
	Order allow,deny
	Allow from localhost 127.0.0.0/8 ::1
	<IfModule mod_fcgid.c>
	    SetHandler fcgid-script
	</IfModule>
	<IfModule !mod_fcgid.c>
	    SetHandler cgi-script
	</IfModule>
</Location>

ScriptAlias /munin-cgi/munin-cgi-html /usr/lib/munin/cgi/munin-cgi-html
<Location /munin-cgi/munin-cgi-html>
	Order allow,deny
	Allow from localhost 127.0.0.0/8 ::1
	<IfModule mod_fcgid.c>
	    SetHandler fcgid-script
	</IfModule>
	<IfModule !mod_fcgid.c>
	    SetHandler cgi-script
	</IfModule>
</Location>
```

/etc/munin/apache24.conf
```
ScriptAlias /munin-cgi/munin-cgi-graph /usr/lib/munin/cgi/munin-cgi-graph
Alias /munin/static/ /var/www/munin/static/

<Directory /var/www/munin>
# added
        Order allow, deny
        Allow from all
# edited
#    Require local
#    Options None
        Require all granted
        Options FollowSymLinks SymLinksIfOwnerMatch
</Directory>

<Directory /usr/lib/munin/cgi>
    Require local
    <IfModule mod_fcgid.c>
        SetHandler fcgid-script
    </IfModule>
    <IfModule !mod_fcgid.c>
        SetHandler cgi-script
    </IfModule>
</Directory>
Alias /munin /var/www/munin
```

/etc/munin/munin-node.conf
```
log_level 4
log_file /var/log/munin/munin-node.log
pid_file /var/run/munin/munin-node.pid

background 1
setsid 1

user root
group root
ignore_file [\#~]$
ignore_file DEADJOE$
ignore_file \.bak$
ignore_file %$
ignore_file \.dpkg-(tmp|new|old|dist)$
ignore_file \.rpm(save|new)$
ignore_file \.pod$
# all - node
allow ^::ffff:127\.0\.0\.1$
# defaults
allow ^127\.0\.0\.1$
allow ^::1$
# nuc - server
allow ^192\.168\.178\.20$
allow ^::ffff:192\.168\.178\.20$
# pizero - server
allow ^192\.168\.178\.30$
allow ^::ffff:192\.168\.178\.30$
host *
port 4949
```

/etc/munin/munin.conf
```
# 
includedir /etc/munin/munin-conf.d
# 
graph_period minute
# 
#htmldir /var/cache/munin/www
htmldir /var/www/munin
max_processes 16
#max_processes 64

[munin;pizero]
    address 127.0.0.1
    use_node_name yes

[munin;fritzbox]
    address 127.0.0.1
    use_node_name no
    
[munin;betlognuc]
    address 192.168.178.20
    use_node_name no

[munin;betlogbrick]
    address 192.168.178.25
    use_node_name no
```

> cat /var/log/munin/munin-node.log

```
2020/01/26-22:40:08 CONNECT TCP Peer: "[::ffff:127.0.0.1]:51702" Local: "[::ffff:127.0.0.1]:4949"
2020/01/26-22:40:08 CONNECT TCP Peer: "[::ffff:127.0.0.1]:51704" Local: "[::ffff:127.0.0.1]:4949"
2020/01/26-22:40:10 [7640] Error output from fritzbox_cpu_temperature.py:
2020/01/26-22:40:10 [7640]      Traceback (most recent call last):
2020/01/26-22:40:10 [7640]        File "/etc/munin/plugins/fritzbox_cpu_temperature.py", line 21, in <module>
2020/01/26-22:40:10 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:10 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:10 [7640]          import requests
2020/01/26-22:40:10 [7640]      ImportError: No module named requests
2020/01/26-22:40:10 [7640] Service 'fritzbox_cpu_temperature.py' exited with status 1/0.
2020/01/26-22:40:10 [7640] Error output from fritzbox_cpu_temperature.py:
2020/01/26-22:40:10 [7640]      Traceback (most recent call last):
2020/01/26-22:40:10 [7640]        File "/etc/munin/plugins/fritzbox_cpu_temperature.py", line 21, in <module>
2020/01/26-22:40:10 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:10 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:10 [7640]          import requests
2020/01/26-22:40:10 [7640]      ImportError: No module named requests
2020/01/26-22:40:10 [7640] Service 'fritzbox_cpu_temperature.py' exited with status 1/0.
2020/01/26-22:40:11 [7640] Error output from fritzbox_wifi_devices.py:
2020/01/26-22:40:11 [7640]      Traceback (most recent call last):
2020/01/26-22:40:11 [7640]        File "/etc/munin/plugins/fritzbox_wifi_devices.py", line 23, in <module>
2020/01/26-22:40:11 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:11 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:11 [7640]          import requests
2020/01/26-22:40:11 [7640]      ImportError: No module named requests
2020/01/26-22:40:11 [7640] Service 'fritzbox_wifi_devices.py' exited with status 1/0.
2020/01/26-22:40:12 [7640] Error output from fritzbox_wifi_devices.py:
2020/01/26-22:40:12 [7640]      Traceback (most recent call last):
2020/01/26-22:40:12 [7640]        File "/etc/munin/plugins/fritzbox_wifi_devices.py", line 23, in <module>
2020/01/26-22:40:12 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:12 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:12 [7640]          import requests
2020/01/26-22:40:12 [7640]      ImportError: No module named requests
2020/01/26-22:40:12 [7640] Service 'fritzbox_wifi_devices.py' exited with status 1/0.
2020/01/26-22:40:12 [7640] Error output from fritzbox_traffic.py:
2020/01/26-22:40:12 [7640]      Traceback (most recent call last):
2020/01/26-22:40:12 [7640]        File "/etc/munin/plugins/fritzbox_traffic.py", line 20, in <module>
2020/01/26-22:40:12 [7640]          from fritzconnection import FritzConnection
2020/01/26-22:40:12 [7640]      ImportError: No module named fritzconnection
2020/01/26-22:40:12 [7640] Service 'fritzbox_traffic.py' exited with status 1/0.
2020/01/26-22:40:12 [7640] Error output from fritzbox_traffic.py:
2020/01/26-22:40:12 [7640]      Traceback (most recent call last):
2020/01/26-22:40:12 [7640]        File "/etc/munin/plugins/fritzbox_traffic.py", line 20, in <module>
2020/01/26-22:40:12 [7640]          from fritzconnection import FritzConnection
2020/01/26-22:40:12 [7640]      ImportError: No module named fritzconnection
2020/01/26-22:40:12 [7640] Service 'fritzbox_traffic.py' exited with status 1/0.
2020/01/26-22:40:26 [7640] Error output from fritzbox_uptime.py:
2020/01/26-22:40:26 [7640]      Traceback (most recent call last):
2020/01/26-22:40:26 [7640]        File "/etc/munin/plugins/fritzbox_uptime.py", line 23, in <module>
2020/01/26-22:40:26 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:26 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:26 [7640]          import requests
2020/01/26-22:40:26 [7640]      ImportError: No module named requests
2020/01/26-22:40:26 [7640] Service 'fritzbox_uptime.py' exited with status 1/0.
2020/01/26-22:40:27 [7640] Error output from fritzbox_uptime.py:
2020/01/26-22:40:27 [7640]      Traceback (most recent call last):
2020/01/26-22:40:27 [7640]        File "/etc/munin/plugins/fritzbox_uptime.py", line 23, in <module>
2020/01/26-22:40:27 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:27 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:27 [7640]          import requests
2020/01/26-22:40:27 [7640]      ImportError: No module named requests
2020/01/26-22:40:27 [7640] Service 'fritzbox_uptime.py' exited with status 1/0.
2020/01/26-22:40:32 [7640] Error output from fritzbox_power_consumption.py:
2020/01/26-22:40:32 [7640]      Traceback (most recent call last):
2020/01/26-22:40:32 [7640]        File "/etc/munin/plugins/fritzbox_power_consumption.py", line 23, in <module>
2020/01/26-22:40:32 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:32 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:32 [7640]          import requests
2020/01/26-22:40:32 [7640]      ImportError: No module named requests
2020/01/26-22:40:32 [7640] Service 'fritzbox_power_consumption.py' exited with status 1/0.
2020/01/26-22:40:33 [7640] Error output from fritzbox_power_consumption.py:
2020/01/26-22:40:33 [7640]      Traceback (most recent call last):
2020/01/26-22:40:33 [7640]        File "/etc/munin/plugins/fritzbox_power_consumption.py", line 23, in <module>
2020/01/26-22:40:33 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:33 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:33 [7640]          import requests
2020/01/26-22:40:33 [7640]      ImportError: No module named requests
2020/01/26-22:40:33 [7640] Service 'fritzbox_power_consumption.py' exited with status 1/0.
2020/01/26-22:40:33 [7640] Error output from fritzbox_connection_uptime.py:
2020/01/26-22:40:33 [7640]      Traceback (most recent call last):
2020/01/26-22:40:33 [7640]        File "/etc/munin/plugins/fritzbox_connection_uptime.py", line 20, in <module>
2020/01/26-22:40:33 [7640]          from fritzconnection import FritzConnection
2020/01/26-22:40:33 [7640]      ImportError: No module named fritzconnection
2020/01/26-22:40:33 [7640] Service 'fritzbox_connection_uptime.py' exited with status 1/0.
2020/01/26-22:40:33 [7640] Error output from fritzbox_connection_uptime.py:
2020/01/26-22:40:33 [7640]      Traceback (most recent call last):
2020/01/26-22:40:33 [7640]        File "/etc/munin/plugins/fritzbox_connection_uptime.py", line 20, in <module>
2020/01/26-22:40:33 [7640]          from fritzconnection import FritzConnection
2020/01/26-22:40:33 [7640]      ImportError: No module named fritzconnection
2020/01/26-22:40:33 [7640] Service 'fritzbox_connection_uptime.py' exited with status 1/0.
2020/01/26-22:40:33 [7640] Error output from fritzbox_cpu_usage.py:
2020/01/26-22:40:33 [7640]      Traceback (most recent call last):
2020/01/26-22:40:33 [7640]        File "/etc/munin/plugins/fritzbox_cpu_usage.py", line 21, in <module>
2020/01/26-22:40:33 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:33 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:33 [7640]          import requests
2020/01/26-22:40:33 [7640]      ImportError: No module named requests
2020/01/26-22:40:33 [7640] Service 'fritzbox_cpu_usage.py' exited with status 1/0.
2020/01/26-22:40:34 [7640] Error output from fritzbox_cpu_usage.py:
2020/01/26-22:40:34 [7640]      Traceback (most recent call last):
2020/01/26-22:40:34 [7640]        File "/etc/munin/plugins/fritzbox_cpu_usage.py", line 21, in <module>
2020/01/26-22:40:34 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:34 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:34 [7640]          import requests
2020/01/26-22:40:34 [7640]      ImportError: No module named requests
2020/01/26-22:40:34 [7640] Service 'fritzbox_cpu_usage.py' exited with status 1/0.
2020/01/26-22:40:34 [7640] Error output from fritzbox_memory_usage.py:
2020/01/26-22:40:34 [7640]      Traceback (most recent call last):
2020/01/26-22:40:34 [7640]        File "/etc/munin/plugins/fritzbox_memory_usage.py", line 21, in <module>
2020/01/26-22:40:34 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:34 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:34 [7640]          import requests
2020/01/26-22:40:34 [7640]      ImportError: No module named requests
2020/01/26-22:40:34 [7640] Service 'fritzbox_memory_usage.py' exited with status 1/0.
2020/01/26-22:40:35 [7640] Error output from fritzbox_memory_usage.py:
2020/01/26-22:40:35 [7640]      Traceback (most recent call last):
2020/01/26-22:40:35 [7640]        File "/etc/munin/plugins/fritzbox_memory_usage.py", line 21, in <module>
2020/01/26-22:40:35 [7640]          import fritzbox_helper as fh
2020/01/26-22:40:35 [7640]        File "/usr/share/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:35 [7640]          import requests
2020/01/26-22:40:35 [7640]      ImportError: No module named requests
2020/01/26-22:40:35 [7640] Service 'fritzbox_memory_usage.py' exited with status 1/0.
2020/01/26-22:40:36 [7640] Error output from irqstats:
2020/01/26-22:40:36 [7640]      Argument "usb_fiq" isn't numeric in addition (+) at /etc/munin/plugins/irqstats line 97, <$in> line 12.
2020/01/26-22:40:37 [7640] Error output from irqstats:
2020/01/26-22:40:37 [7640]      Argument "usb_fiq" isn't numeric in addition (+) at /etc/munin/plugins/irqstats line 97, <$in> line 12.
2020/01/26-22:40:41 [7640] Error output from fritzbox_helper.py:
2020/01/26-22:40:41 [7640]      Traceback (most recent call last):
2020/01/26-22:40:41 [7640]        File "/etc/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:41 [7640]          import requests
2020/01/26-22:40:41 [7640]      ImportError: No module named requests
2020/01/26-22:40:41 [7640] Service 'fritzbox_helper.py' exited with status 1/0.
2020/01/26-22:40:42 [7640] Error output from fritzbox_helper.py:
2020/01/26-22:40:42 [7640]      Traceback (most recent call last):
2020/01/26-22:40:42 [7640]        File "/etc/munin/plugins/fritzbox_helper.py", line 26, in <module>
2020/01/26-22:40:42 [7640]          import requests
2020/01/26-22:40:42 [7640]      ImportError: No module named requests
2020/01/26-22:40:42 [7640] Service 'fritzbox_helper.py' exited with status 1/0.
```

> cat /var/log/munin/munin-update.log
```
2020/01/26 22:45:04 [INFO]: Starting munin-update
2020/01/26 22:45:08 [INFO] starting work in 8052 for fritzbox/127.0.0.1:4949.
2020/01/26 22:45:08 [INFO] starting work in 8051 for pizero/127.0.0.1:4949.
2020/01/26 22:45:08 [INFO] starting work in 8049 for betlogbrick/192.168.178.25:4949.
2020/01/26 22:45:08 [INFO] starting work in 8050 for betlognuc/192.168.178.20:4949.
2020/01/26 22:45:08 [INFO] node fritzbox advertised itself as pizero.fritz.box instead.
2020/01/26 22:45:08 [WARNING] Config node fritzbox listed no services for fritzbox, (advertised as pizero.fritz.box).  Please see http://munin-monitoring.org/wiki/FAQ_no_graphs for further information.
2020/01/26 22:45:08 [INFO]: Munin-update finished for node munin;fritzbox (0.37 sec)
2020/01/26 22:45:08 [INFO] node pizero advertised itself as pizero.fritz.box instead.
2020/01/26 22:45:18 [INFO] Remaining workers: munin;betlogbrick, munin;pizero, munin;betlognuc
2020/01/26 22:45:18 [INFO] Reaping Munin::Master::UpdateWorker<munin;fritzbox>.  Exit value/signal: 0/0
2020/01/26 22:45:20 [INFO]: Munin-update finished for node munin;betlogbrick (12.31 sec)
2020/01/26 22:45:27 [INFO]: Munin-update finished for node munin;betlognuc (18.49 sec)
2020/01/26 22:45:27 [INFO] Reaping Munin::Master::UpdateWorker<munin;betlogbrick>.  Exit value/signal: 0/0
2020/01/26 22:45:37 [INFO] Remaining workers: munin;pizero
2020/01/26 22:45:37 [INFO] Reaping Munin::Master::UpdateWorker<munin;betlognuc>.  Exit value/signal: 0/0
2020/01/26 22:45:41 [INFO]: Munin-update finished for node munin;pizero (33.39 sec)
2020/01/26 22:45:42 [INFO] Reaping Munin::Master::UpdateWorker<munin;pizero>.  Exit value/signal: 0/0
2020/01/26 22:45:44 [INFO]: Munin-update finished (39.68 sec)
```

> cat /var/log/munin/munin-html.log

```
2020/01/26 22:46:00 [INFO] Starting munin-html, getting lock /var/run/munin/munin-html.lock
2020/01/26 22:46:59 [INFO] Creating problem page /var/www/munin/problems.html
2020/01/26 22:46:59 [INFO] Releasing lock file /var/run/munin/munin-html.lock
2020/01/26 22:46:59 [INFO] munin-html finished (59.16 sec)
```

> /var/log/munin/munin-html.log

```
2020/01/26 22:46:00 [INFO] config generated (9.28 sec)
2020/01/26 22:46:00 [INFO] Starting munin-html, getting lock /var/run/munin/munin-html.lock
2020/01/26 22:46:59 [INFO] Creating problem page /var/www/munin/problems.html
2020/01/26 22:46:59 [INFO] Releasing lock file /var/run/munin/munin-html.lock
2020/01/26 22:46:59 [INFO] munin-html finished (59.16 sec)
```

**Comment by sumpfralle** [comment]
Thank you for your report!

I think, you misunderstood the way munin works. The port 4949 is provided by `munin-node` and does not *speak* HTTP, but the munin protocol instead. This port is used by the munin master to retrieve data from remote or local systems.

Instead you need to configure your webserver (e.g. apache2) for presenting the collected data of the munin master.

At least for Debian this is fully configured by the packaging and should work out of the box.

I am quite sure, that your painful endeavour was caused by a missing or misleading piece of documentation within munin. Do you have an idea, where we could add or change something to prevent this?

**Comment by BETLOG** [comment]
>the way munin works. The port 4949 

doh

> Instead you need to configure your webserver (e.g. apache2) for presenting the collected data of the munin master.

Is this documented somewhere that you can recommend? Chances are I have already read it and just need to review it in light of the above enlightenment.

Does the supplied /etc/munin/apache24.conf need to be manually edited into /etc/apache2/apache2.conf or is it loaded some other way?


> your painful endeavour was caused by a missing or misleading piece of documentation

I spent literally all day yesterday, and significant parts of numerous prior days/nights pondering this,  and have read so many documents, and tried so many variants of things that to be honest I really can't tell. However as I come to understand it better I will report any epiphanies I have re: that question.

That said: I do feel some confusion arises from :
a) the sheer age of many of the google-able web results
b) pages that suggest editing  /var/cache/www/munin   to  /var/www/munin

and also I'd like to report a workaround, that trivially allows me to view the html via ssh

```
mkdir /tmp/munin
sshfs pi@pizero:/var/www/munin /tmp/munin
google-chrome /tmp/munin/index.html &

```
Not ideal, but I don't see any downsides to proper web service, and at least I can actually see them now.

**Comment by BETLOG** [comment]
As an example, I just googled "/var/cache/www/munin" to check if i was recalling the path correctly  while writing the above, and this post is exactly what I am experiencing... with no answer.
https://serverfault.com/questions/461599/should-munin-sit-in-var-www-munin-or-var-cache-munin-www

Perhaps the *official* munin documentation is not appearing prominently enough in search results that ask a problematic question.. ie: the type of topic wording from the link above.

Also perhaps the official documentation needs a very wide angle overview of the process and mechanisms. I don't think I have seen one of those. Had I initially known that I should not be expecting web content on 4949 I'm sure I would not have become entangled.

**Comment by BETLOG** [comment]
lol, i just changed /etc/apache2/sites-available/munin.conf
<VirtualHost *:4949> 
to
<VirtualHost *:80> 
restarted apache2, and it works.

So yes, evidently I was confused about the purpose of port 4949 :)
